### ISSUE TITLE
Explore the use of as-pect

### ISSUE THREAD

**Issue by ColinEberhardt** [ColinEberhardt/assemblyscript-regex#15]
I previously tried as-pect, but hit an issue of some sort. I honestly can't recall what it was now. In the spirit of supporting the AssemblyScript ecosystem, it would be good to se as-pect.

/cc @jtenner

**Comment by jtenner** [comment]
Hello @ColinEberhardt. Currently the issue is that the garbage collector keeps changing underneath me. It's entirely possible this won't take long, but each time assemblyscript iterates a new version, something comes up and breaks. I am actively working on this, and will keep you posted.

Many thanks!

**Comment by ColinEberhardt** [comment]
Thanks you @jtenner - really appreciate all your hard work. I'm not in a hurry, can keep going on v0.17 as I have quite a bit more work to do on the regex engine itself.
